language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

arch:
  - amd64
  - ppc64le

sudo: false

env:
  global:
    - COVERAGE_PROCESS_START=".coveragerc"

before_install:
  - pip install nose coverage coveralls

script:
  - nosetests -v --with-coverage --cover-package=jsonrpclib tests

after_success:
  - coveralls
